apiVersion: v1
kind: Service
metadata:
  name: snmse-users-service
spec:
  selector: # select the pod
    app: snmse-users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001